
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cgoynwbrmojzckrjsfel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNnb3lud2JybW9qemNrcmpzZmVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4ODIzODcsImV4cCI6MjA2MjQ1ODM4N30.8mkd0PL7yfJbYNcxMbmI5dvMqgTZmGgmtaC86ArVs-U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true
  },
  // Add global error handling for easier debugging
  global: {
    headers: {
      'Content-Type': 'application/json'
    }
  }
});
